import { getData } from "@/components/data_loading/data_loading";
import type { Filters } from "../../types";
import { columns } from "./columns";
import { ResponseDataTable } from "./data-table";

interface ResponsesPageProps {
  page: Filters;
}

export default async function ResponsesPage({ page }: ResponsesPageProps) {
  const data = await getData();

  return (
    <div className="container mx-auto py-5">
      <ResponseDataTable columns={columns} data={data} page={page} />
    </div>
  );
}

// export const exampleData: Response[] = [
//   {
//     contact_status: "accepted",
//     dob: "09/23/2005",
//     email: "katherine@college.harvard.edu",
//     gender: "non-binary",
//     id: 123,
//     is_duplicate: false,
//     is_processed: true,
//     is_waitlisted: true,
//     won_at: "02/22/2024",
//     name: "Katherine",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "1112223333",
//     unwaitlisted_at: "03/08/2024",
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Katherine noted she prefers the woman's lottery, but would be okay being in either.",
//     additional_info: "",
//     other_contact: null,
//     duplicate_ids: [],
//     has_won: true,
//   },
//   {
//     contact_status: "awaiting response",
//     dob: "09/23/2005",
//     email: "ellie@college.harvard.edu",
//     gender: "woman",
//     id: 117,
//     is_duplicate: false,
//     is_processed: true,
//     is_waitlisted: true,
//     won_at: "03/23/2024",
//     name: "Ellie",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "1112223333",
//     unwaitlisted_at: "03/08/2024",
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Ellie will no longer need a bed after April 20th 2024",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "awaiting response",
//     dob: "09/23/2005",
//     email: "chris@college.harvard.edu",
//     gender: "man",
//     id: 126,
//     is_duplicate: false,
//     is_processed: true,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "John",
//     lottery_type: "man",
//     lottery_info: null,
//     waitlisted_at: null,
//     phone: "1234567890",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "John confirmed acceptance.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "awaiting response",
//     dob: "06/12/1999",
//     email: "susan@college.harvard.edu",
//     gender: "woman",
//     id: 127,
//     is_duplicate: true,
//     is_processed: false,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "Susan",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "9876543210",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Awaiting Susan's response.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "awaiting response",
//     dob: "06/12/1999",
//     email: "susan@college.harvard.edu",
//     gender: "woman",
//     id: 130,
//     is_duplicate: true,
//     is_processed: false,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "Susann",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "9876543210",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Awaiting Susan's response.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "no response",
//     dob: "04/30/2002",
//     email: "alex@college.harvard.edu",
//     gender: "non-binary",
//     id: 128,
//     is_duplicate: true,
//     is_processed: true,
//     is_waitlisted: false,
//     won_at: "02/23/2024",
//     name: "Alex",
//     lottery_type: "man",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "9871234560",
//     unwaitlisted_at: "04/03/2024",
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "No response from Alex yet.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "declined",
//     dob: "03/15/2001",
//     email: "emily@college.harvard.edu",
//     gender: "non-binary",
//     id: 129,
//     is_duplicate: false,
//     is_processed: true,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "Emily",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: null,
//     phone: "1239876540",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Emily has declined the offer.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "awaiting response",
//     dob: "08/18/2000",
//     email: "kim@college.harvard.edu",
//     gender: "non-binary",
//     id: 131,
//     is_duplicate: false,
//     is_processed: false,
//     is_waitlisted: false,
//     won_at: "02/23/2024",
//     name: "Kim",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "1239876543",
//     unwaitlisted_at: "03/24/2024",
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Waiting for Kim's response.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "no response",
//     dob: "02/28/2004",
//     email: "ryan@college.harvard.edu",
//     gender: "man",
//     id: 132,
//     is_duplicate: false,
//     is_processed: false,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "Ryan",
//     lottery_type: "man",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "9876543219",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "No response from Ryan.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "declined",
//     dob: "10/15/2005",
//     email: "jessica@college.harvard.edu",
//     gender: "woman",
//     id: 133,
//     is_duplicate: false,
//     is_processed: true,
//     is_waitlisted: false,
//     won_at: "02/23/2024",
//     name: "Jessica",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: null,
//     phone: "1234569870",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Jessica has declined.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "no response",
//     dob: "04/30/2002",
//     email: "alex@college.harvard.edu",
//     gender: "non-binary",
//     id: 134,
//     is_duplicate: true,
//     is_processed: true,
//     is_waitlisted: false,
//     won_at: "02/23/2024",
//     name: "Alexi",
//     lottery_type: "man",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "9871234560",
//     unwaitlisted_at: "03/22/2024",
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "No response from Alex yet.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "awaiting response",
//     dob: "09/12/2001",
//     email: "ashley@college.harvard.edu",
//     gender: "woman",
//     id: 135,
//     is_duplicate: false,
//     is_processed: false,
//     is_waitlisted: false,
//     won_at: "02/23/2024",
//     name: "Ashley",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: null,
//     phone: "1239876543",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Awaiting Ashley's response.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "no response",
//     dob: "03/28/2002",
//     email: "michael@college.harvard.edu",
//     gender: "man",
//     id: 136,
//     is_duplicate: false,
//     is_processed: false,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "Michael",
//     lottery_type: "man",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "9876543219",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "No response from Michael yet.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "declined",
//     dob: "12/15/2005",
//     email: "sophia@college.harvard.edu",
//     gender: "woman",
//     id: 137,
//     is_duplicate: false,
//     is_processed: true,
//     is_waitlisted: false,
//     won_at: "02/23/2024",
//     name: "Sophia",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: null,
//     phone: "1234569870",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Sophia has declined.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "accepted",
//     dob: "04/08/2003",
//     email: "austin@college.harvard.edu",
//     gender: "man",
//     id: 138,
//     is_duplicate: false,
//     is_processed: true,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "Austin",
//     lottery_type: "man",
//     lottery_info: null,
//     waitlisted_at: null,
//     phone: "9876543210",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Austin accepted the offer.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "awaiting response",
//     dob: "01/12/2001",
//     email: "emily@college.harvard.edu",
//     gender: "woman",
//     id: 139,
//     is_duplicate: false,
//     is_processed: false,
//     is_waitlisted: false,
//     won_at: "02/23/2024",
//     name: "Emily",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: null,
//     phone: "1239876543",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Waiting for Emily's response.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "no response",
//     dob: "05/28/2002",
//     email: "nathan@college.harvard.edu",
//     gender: "man",
//     id: 140,
//     is_duplicate: false,
//     is_processed: true,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "Nathan",
//     lottery_type: "man",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "9876543219",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "No response from Nathan yet.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "declined",
//     dob: "11/15/2005",
//     email: "olivia@college.harvard.edu",
//     gender: "non-binary",
//     id: 141,
//     is_duplicate: false,
//     is_processed: false,
//     is_waitlisted: false,
//     won_at: "02/23/2024",
//     name: "Olivia",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: null,
//     phone: "1234569870",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Olivia has declined.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "accepted",
//     dob: "09/08/2003",
//     email: "ryan@college.harvard.edu",
//     gender: "man",
//     id: 142,
//     is_duplicate: false,
//     is_processed: true,
//     is_waitlisted: false,
//     won_at: "02/23/2024",
//     name: "Ryan",
//     lottery_type: "man",
//     lottery_info: null,
//     waitlisted_at: null,
//     phone: "9876543210",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Ryan accepted the offer.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "awaiting response",
//     dob: "02/12/2001",
//     email: "maya@college.harvard.edu",
//     gender: "woman",
//     id: 143,
//     is_duplicate: false,
//     is_processed: false,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "Maya",
//     lottery_type: "woman",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "1239876543",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "Waiting for Maya's response.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     contact_status: "no response",
//     dob: "04/28/2002",
//     email: "matthew@college.harvard.edu",
//     gender: "non-binary",
//     id: 144,
//     is_duplicate: false,
//     is_processed: false,
//     is_waitlisted: true,
//     won_at: "02/23/2024",
//     name: "Matthew",
//     lottery_type: "man",
//     lottery_info: null,
//     waitlisted_at: "03/08/2024",
//     phone: "9876543219",
//     unwaitlisted_at: null,
//     uploaded_at: "03/08/2024",
//     submitted_at: "02/20/2024",
//     notes: "No response from Matthew yet.",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     id: 124,
//     won_at: null,
//     is_duplicate: false,
//     name: "John",
//     gender: "man",
//     lottery_type: "man",
//     lottery_info: null,
//     dob: "05/12/1990",
//     email: "john@example.com",
//     phone: "5556667777",
//     submitted_at: "03/25/2024",
//     notes: "John's entry received.",
//     is_waitlisted: false,
//     waitlisted_at: null,
//     unwaitlisted_at: null,
//     is_processed: true,
//     contact_status: "accepted",
//     uploaded_at: "03/26/2024",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: false,
//   },
//   {
//     id: 118,
//     won_at: "03/29/2024",
//     is_duplicate: false,
//     name: "Maria",
//     gender: "woman",
//     lottery_type: "woman",
//     lottery_info: null,
//     dob: "12/15/1988",
//     email: "maria@example.com",
//     phone: "9998887777",
//     submitted_at: "03/01/2024",
//     notes: "Maria emailed she no longer needs housing",
//     is_waitlisted: false,
//     waitlisted_at: null,
//     unwaitlisted_at: "02/24/24",
//     is_processed: true,
//     contact_status: "not contacted",
//     uploaded_at: "03/02/2024",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: true,
//   },
//   {
//     id: 127,
//     won_at: null,
//     is_duplicate: false,
//     name: "Alex",
//     gender: "non-binary",
//     lottery_type: null,
//     lottery_info: null,
//     dob: "09/02/1975",
//     email: "alex@example.com",
//     phone: "3334445555",
//     submitted_at: "03/10/2024",
//     notes: "",
//     is_waitlisted: false,
//     waitlisted_at: null,
//     unwaitlisted_at: null,
//     is_processed: false,
//     contact_status: null,
//     uploaded_at: "03/11/2024",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: false,
//   },
//   {
//     id: 129,
//     won_at: null,
//     is_duplicate: true,
//     name: "Kim",
//     gender: "woman",
//     lottery_type: "woman",
//     lottery_info: null,
//     dob: "02/28/1995",
//     email: "kim@example.com",
//     phone: "7778889999",
//     submitted_at: "03/20/2024",
//     notes: "Kim's entry received.",
//     is_waitlisted: false,
//     waitlisted_at: null,
//     unwaitlisted_at: null,
//     is_processed: false,
//     contact_status: null,
//     uploaded_at: "03/21/2024",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: false,
//   },
//   {
//     id: 130,
//     won_at: null,
//     is_duplicate: true,
//     name: "Kim",
//     gender: "woman",
//     lottery_type: "woman",
//     lottery_info: null,
//     dob: "02/28/1995",
//     email: "kim@example.com",
//     phone: "7778889999",
//     submitted_at: "03/20/2024",
//     notes: "Kim's entry received.",
//     is_waitlisted: false,
//     waitlisted_at: null,
//     unwaitlisted_at: null,
//     is_processed: false,
//     contact_status: null,
//     uploaded_at: "03/21/2024",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: false,
//   },
//   {
//     id: 128,
//     won_at: null,
//     is_duplicate: false,
//     name: "Keiko",
//     gender: "woman",
//     lottery_type: "woman",
//     lottery_info: null,
//     dob: "05/12/1990",
//     email: "ktanaka@example.com",
//     phone: "5556667777",
//     submitted_at: "03/25/2024",
//     notes: "emailed about smthg",
//     is_waitlisted: false,
//     waitlisted_at: null,
//     unwaitlisted_at: null,
//     is_processed: false,
//     contact_status: "awaiting response",
//     uploaded_at: "03/26/2024",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: false,
//   },
//   {
//     id: 124,
//     won_at: null,
//     is_duplicate: false,
//     name: "John",
//     gender: "man",
//     lottery_type: "man",
//     lottery_info: null,
//     dob: "05/12/1990",
//     email: "john@example.com",
//     phone: "5556667777",
//     submitted_at: "03/25/2024",
//     notes: "John's entry received.",
//     is_waitlisted: false,
//     waitlisted_at: null,
//     unwaitlisted_at: null,
//     is_processed: false,
//     contact_status: "awaiting response",
//     uploaded_at: "03/26/2024",
//     other_contact: null,
//     duplicate_ids: [],
//     additional_info: "",
//     has_won: false,
//   },
// ];

// async function getData(): Promise<Response[]> {
//   // Fetch data from your API here.
//   const data = await Promise.resolve(exampleData);
//   return data;
// }
